[STORAGE]
AWS_URL_DIR = https://blent-learning-user-ressources.s3.eu-west-3.amazonaws.com/projects/9c15cb
BUCKET_NAME = blent_spark_bucket5
# Char "%" is doubled for Python's compatibility
date_format = %%Y-%%m-%%d %%H:%%M:%%S
STORAGE_TRANSFER_VERSION = 1.19.0  # max version compatible with Python 3.8

[SPARK_SCRIPT_DEFAULTS]
DATE_START = 2019-12-16 00:00:00
DATE_END = 2020-01-15 00:00:00
# RAW DIR is Spark Job's input and Transfer Job's output
GCS_REL_RAW_DIR = data/raw/blent-learning-user-ressources.s3.eu-west-3.amazonaws.com/projects/9c15cb
GCS_REL_PROCESSED_DIR = data/processed

[LOGGING]
level = INFO
format = ▶️ %%(asctime)s: %%(message)s

[GENERAL]
HELP_DATE_FORMAT = YYYY-MM-DD HH:MM:SS

