[STORAGE]
AWS_URL_DIR = https://blent-learning-user-ressources.s3.eu-west-3.amazonaws.com/projects/9c15cb
BUCKET_NAME = blent_spark_bucket5
REGION = us-central1
# Char "%" is doubled for Python's compatibility
DATE_FORMAT = %%Y-%%m-%%d %%H:%%M:%%S

[TRANSFER]
# RAW DIR is Transfer Job's output
REL_RAW_DIR = data/raw

[SPARK_SCRIPT_DEFAULTS]
DATE_START = 2019-12-16 00:00:00
DATE_END = 2020-01-15 00:00:00
# RAW DIR is Spark Job's input
REL_RAW_DIR = data/raw/blent-learning-user-ressources.s3.eu-west-3.amazonaws.com/projects/9c15cb
REL_PROCESSED_DIR = data/processed

[LOGGING]
LOG_LEVEL = INFO
LOG_FORMAT = ▶️ %%(asctime)s: %%(message)s
# Leave log directory empty to avoid creating a log file
LOG_DIR = ./log

[GENERAL]
HELP_DATE_FORMAT = YYYY-MM-DD HH:MM:SS
